Add conditional mach/error.h include for compatibility
duck2/uxsdcxx pull request #51
Opened 2020-04-27 19:58 UTC by HackerFoo

Otherwise the generated output will not compile on Mac OS.

2020-04-27 21:00 UTC, litghost commented
Is this header actually required?  Can we just eliminate it?

2020-04-27 21:08 UTC, HackerFoo commented
It compiles without it, but I'm not sure that it's never needed. I see some references to `errno`. I'm fine with removing it.

2020-04-27 21:09 UTC, litghost commented
> It compiles without it, but I'm not sure that it's never needed. I see some references to `errno`. I'm fine with removing it.

`errno` should be supplied from `errno.h` or `cerrno`, not `error.h`?

2020-04-29 00:01 UTC, litghost requested changes
Poke?

2020-04-29 02:17 UTC, HackerFoo commented
I've removed the include.

2020-04-30 17:02 UTC, litghost commented
LGTM and good to merge if you've tested this with VTR on Linux and Mac OS X

2020-04-30 17:25 UTC, merged